name: image-classification
functions:
  # Yaml by local reference
  - url: utils.yaml
    name: utils
  # Yaml by github URL
  - url: https://raw.githubusercontent
  - .com/mlrun/demo-image-classification/master/notebooks/nuclio-serving-tf
  - -images.ipynb
    name: serving
workflows:
  main: ./py/workflow.py