name: image-classification
functions:
  # Yaml by local reference
  - url: ./yaml/utils.yaml
    name: utils
  - url: ./yaml/trainer.yaml
    name: trainer
  # Yaml by github URL
  - url: notebooks/nuclio-serving-tf-images.ipynb
    name: serving
    kind: nuclio:serving
workflows:
  - name: main
    code: src/workflow.py