kind: mpijob
metadata:
  name: horovod-trainer
  tag: latest
  hash: f45c6391606c2c9f12c8a31e2ece057d1ced5aa6
  project: default
  categories: []
spec:
  command: /User/my-proj/src/horovod-training.py
  args: []
  image: mlrun/mpijob:latest
  env:
  - name: V3IO_API
    value: ''
  - name: V3IO_USERNAME
    value: ''
  - name: V3IO_ACCESS_KEY
    value: ''
  description: ''
  replicas: 4
  image_pull_policy: Always
  build:
    commands: []
