kind: mpijob
metadata:
  name: horovod-trainer
  tag: latest
  hash: ca9b2f2453afddcb69c1cc7360687249062abb96
  project: default
spec:
  command: /User/demo-image-classification/src/horovod-training.py
  args: []
  image: mlrun/mpijob:latest
  env:
  - name: V3IO_API
    value: ''
  - name: V3IO_USERNAME
    value: ''
  - name: V3IO_ACCESS_KEY
    value: ''
  description: ''
  replicas: 4
  image_pull_policy: Always
  build:
    commands: []
